class Test5 extends Exception { }



class Main {

public static void main(String args[]) {

try {

throw new Test5();

}

catch(Test5 t) {

System.out.println("Got the Test Exception");

}

finally {

System.out.println("Inside finally block ");

}

}

}
